<div class="mx-4 my-4 lg:my-8 lg:mx-32 font-SourceSansPro text-base text-justify space-y-4">
    <div class="lg:mx-40">
        <div class="bg-biru text-white text-center items-center font-Montserrat font-bold lg:text-4xl py-2 text-lg">"Semua Finisher akan mendapatkan medali, sesuai batas waktu yang ditentukan"</div>
        <p class="text-sm mt-2">* batas waktu ditentukan pada saat technical meeting.</p>
    </div>
    <p class="indent-16">Menjawab sebuah pertanyaan besar saat ini, kapan ada event besar di kota madiun? Pertanyaan tsb sering terucap dari rekan2 dari berbagai kota2 di indonesia, karena serignya kita issi kota madiun mengikuti event/kejuaraan balap sepeda diberbagai kota di indonesia.</p>
    <p class="indent-16"> Memang mulai tahun 2019 pun hampir tiap tahun sudah dimulai event2 balap sepeda di madiun, namun msh terbatas dan blm bersifat internasional. Kali ini merupakan sebuah terobosan yang digagas oleh  BUMN di kota madiun kerjasama dengan issi kota madiun dan juga pemerintah kota madiun menggelar sebuah event balap sepeda dengan tema sport tourism. Salah satu langkah juga mendukung program bapak walikota madiun yang telah melakukan perubahan besar wajah kota madiun. Kami selaku induk olahraga bersepeda di kota madiun membuat sebuah kemasan kegiatan dengan mengangkat konsep sport tourism yakni olahraga dg misi prestasi dan wisata.</p>
    <p class="indent-16">MLC "MADIUN LAWU CHALLENGGE" kegiatan selama 3 hari berpusat di kota madiun, nantinya kota madiun akan kedatangan tamu dari berbagai kota di indonesia dan juga beberapa negara yg akan hadir dalam MLC.  Hari pertama akan dibuka dengan kegiatan funbike bersama bapak walikota madiun bersama warga masyarakat kota madiun serta undangan dan juga sebagian peserta MLC yg telah hadir, hari kedua peserta KOM akan diuji mendaki gunung lawu dengan jarak tempuh 70km yang akan start dari balai kota madiun dan finish di cemoro sewu perbatasan jawa timur dan jawa tengah juaranya akan mendaoat gelar Raja Tanjakan (KOM "King of Mountain) dan (QOM "Queen of Mountain)</p>
    <p class="indent-16">Hari ketiga peserta akan diadu cepat dalam sirkuit di kota madiun dalam acara criterium yang akan mempertandingkan berbagai kelas dari usia dini, pelajar, atlet, hobbies, hingga mantan atlet.
    Diharapkan kegiatan MLC ini akan berdampak langsung pada pemulihan ekonomi di kota madiun dan juga berdampak multiplayer effect juga di kota madiun. Selanjutnya juga akan menjadikan kegiatan tahunan rutin yang akan selalu ditunggu tunggu oleh seluruh peserta dan masyarakat kota madiun ke depan.</p>
</div>