@extends('layout.main')
@section('navbar')
    @include('components.navbar')
@endsection
@section('content')
    @include('layout.navbar')
    @include('components.mlc_register_head')
    @include('components.mlc_register_success')
@endsection
@section('footer')
    @include('components.footer')
@endsection